### ISSUE TITLE
hg64_get pmax parameter is not exclusive as the documentation implies

### ISSUE THREAD

**Issue by davidmankin** [fanf2/hg64#1]
Hi,
I was porting hg64 from C to Rust.  It seems to have gone pretty well except that I noticed that the docs for the pmax outparam for hg64_get doesn't match the behavior (of my port, at least).  It seems to return the max value _inclusive_ instead of _exclusive_ as the comments show. 

In Rust to meet the comment I had to use 
```rust
        let max = get_maxval(key).saturating_add(1);
```

At first I tried `+1` but rust panicked when the `get_maxval` returns `u64::MAX`.

I'm not sure whether you'd rather update the pmax documentation or add one to it carefully.

**Comment by fanf2** [comment]
Hello! Thanks for taking an interest in my little project: porting it to Rust sounds like an excellent idea :-)

The comment is wrong, and I failed to adjust it in commit 30ec126ae7. And Rust is giving you a strong hint about why the comment is wrong: the top-most bucket has to span a range up to `UINT64_MAX` so it's obviously impossible to return an _exclusive_ bound _inside_ a `uint64_t`.

I will fix this shortly, thanks for th bug report!

Would you like me to add a link to your Rust version in my README?

**Comment by davidmankin** [comment]
Thanks!  I saw the project on Hacker News and I always have a desire to have better/cheaper percentile calculations so I looked into it.  Since I don't touch raw C anymore, it seemed like a good project to use to learn some Rust too. 

I'm just starting with Rust so for the time being it's really rough. When it's in any sort of shape to share I'd be happy to cross link.

**Comment by fanf2** [comment]
I hope you're enjoying Rust, it's a fun workout for the little grey cells :-)

**Comment by davidmankin** [comment]
https://github.com/davidmankin/hg64rs is my code if you're curious to take a look.  Now that I see how much overhaul you've done on the without-popcount branch I may try to turn it into a second rust library when I find some time.
